---
- hosts: 172.31.8.215
  become: yes
  tasks:
  - name: install webserver
    apt:
      name: apache2
      state: present
    notify:
     - restartapache2
     - nodeos
    

  handlers:
  - name: restartapache2
    service:
         name: apache2
         state: restarted
  - name: nodeos 
    debug:
       msg: "{{ansble_os_family}}"


